### ISSUE TITLE
AttributeError: module 'sqlalchemy.types' has no attribute 'Binary'

### ISSUE THREAD

**Issue by eyalk** [pudo/dbcopy#2]
Hi 
When running  dbcopy --help I am getting "AttributeError: module 'sqlalchemy.types' has no attribute 'Binary'"

How do I fix it?

Thanks.

Traceback (most recent call last):
  File "d:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\Python\Python39\Scripts\dbcopy.exe\__main__.py", line 4, in <module>
  File "d:\python\python39\lib\site-packages\dbcopy\cli.py", line 5, in <module>
    from dbcopy.db import Database
  File "d:\python\python39\lib\site-packages\dbcopy\db.py", line 14, in <module>
    class Database(object):
  File "d:\python\python39\lib\site-packages\dbcopy\db.py", line 26, in Database
    mssql.base.TIMESTAMP: types.Binary,
AttributeError: module 'sqlalchemy.types' has no attribute 'Binary'

**Comment by pudo** [comment]
Oh I think this may be the same thing as #1, I'll make a release - try `pip install --upgrade dbcopy` later.

**Comment by pudo** [comment]
cf. 0.1.7.
